# Install-time script (see Packaging.cmake): installs the scenes in MIRAS_SCENES and the model files they
# reference, keeping their paths relative to the executable's folder. Inputs: MIRAS_EXE_DIR, MIRAS_SCENES,
# MIRAS_MODEL_CACHES. Reads the format SceneSerializer.h writes.

# Little-endian uint32 at a byte offset of a file read with file(READ ... HEX).
function(miras_read_u32 hex byteOffset out)
    math(EXPR charOffset "${byteOffset} * 2")
    string(SUBSTRING "${hex}" ${charOffset} 8 word)
    string(REGEX REPLACE "(..)(..)(..)(..)" "\\4\\3\\2\\1" word "${word}")
    math(EXPR value "0x${word}")
    set(${out} ${value} PARENT_SCOPE)
endfunction()

function(miras_read_string hex byteOffset length out)
    math(EXPR charOffset "${byteOffset} * 2")
    math(EXPR charLength "${length} * 2")
    string(SUBSTRING "${hex}" ${charOffset} ${charLength} bytesHex)
    string(REGEX MATCHALL ".." bytes "${bytesHex}")
    set(text "")
    foreach(byte IN LISTS bytes)
        math(EXPR code "0x${byte}")
        string(ASCII ${code} char)
        string(APPEND text "${char}")
    endforeach()
    set(${out} "${text}" PARENT_SCOPE)
endfunction()

function(miras_install_relative relativePath)
    get_filename_component(dir "${relativePath}" DIRECTORY)
    file(INSTALL "${MIRAS_EXE_DIR}/${relativePath}" DESTINATION "${CMAKE_INSTALL_PREFIX}/${dir}")
endfunction()

set(installedModels "")
foreach(scene IN LISTS MIRAS_SCENES)
    if (NOT EXISTS "${MIRAS_EXE_DIR}/${scene}")
        message(WARNING "Scene ${MIRAS_EXE_DIR}/${scene} not found; it is not packaged")
        continue()
    endif()
    miras_install_relative("${scene}")

    # SceneFileHeader: "SCNE", version, modelCount, instanceCount. Then per model: SceneModelEntry
    # (pathLength, nameLength), the path and the name.
    file(READ "${MIRAS_EXE_DIR}/${scene}" hex HEX)
    string(SUBSTRING "${hex}" 0 8 magic)
    if (NOT magic STREQUAL "53434e45")
        message(WARNING "${scene} is not a scene file; its models are not packaged")
        continue()
    endif()
    miras_read_u32("${hex}" 8 modelCount)
    set(offset 16)
    set(index 0)
    while (index LESS modelCount)
        miras_read_u32("${hex}" ${offset} pathLength)
        math(EXPR nameOffset "${offset} + 4")
        miras_read_u32("${hex}" ${nameOffset} nameLength)
        math(EXPR offset "${offset} + 8")
        miras_read_string("${hex}" ${offset} ${pathLength} path)
        math(EXPR offset "${offset} + ${pathLength} + ${nameLength}")
        math(EXPR index "${index} + 1")

        string(REGEX REPLACE "^ifcdirect:" "" path "${path}")
        if (path MATCHES "^builtin:" OR path IN_LIST installedModels)
            continue()
        endif()
        if (IS_ABSOLUTE "${path}")
            message(WARNING "${scene} uses ${path} by absolute path; it is not packaged and won't be found "
                "on other PCs. Move it next to engine.exe (e.g. into models/) and save the scene again.")
            continue()
        endif()
        if (NOT EXISTS "${MIRAS_EXE_DIR}/${path}")
            message(WARNING "${scene} uses ${path}, which does not exist")
            continue()
        endif()
        list(APPEND installedModels "${path}")
        miras_install_relative("${path}")
        if (MIRAS_MODEL_CACHES AND EXISTS "${MIRAS_EXE_DIR}/${path}.cache")
            miras_install_relative("${path}.cache")
        endif()
    endwhile()
endforeach()
